import psycopg2
import psycopg2.extras
import json
from config.settings import settings
import logging

logger = logging.getLogger(__name__)

def get_connection():
    return psycopg2.connect(settings.database_url)

def create_expert(expert_id: str, name: str, role: str, domain: str):
    """Creates or updates an expert record."""
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                INSERT INTO experts (id, name, role, domain)
                VALUES (%s, %s, %s, %s)
                ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, role=EXCLUDED.role, domain=EXCLUDED.domain
                RETURNING id;
            """, (expert_id, name, role, domain))
            return cur.fetchone()[0]

def create_extraction_session(session_id: str, expert_id: str):
    """Creates a new extraction session."""
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                INSERT INTO extraction_sessions (id, expert_id, status)
                VALUES (%s, %s, 'in_progress')
                RETURNING id;
            """, (session_id, expert_id))
            return cur.fetchone()[0]

def update_session_status(session_id: str, status: str, current_node: str = None, error: str = None):
    """Updates the session status."""
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                UPDATE extraction_sessions SET status = %s, current_node = %s, error = %s, updated_at = now() WHERE id = %s
            """, (status, current_node, error, session_id))

def get_session(session_id: str):
    """Fetches session metadata."""
    with get_connection() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
            cur.execute("SELECT * FROM extraction_sessions WHERE id = %s", (session_id,))
            return cur.fetchone()

def save_scenarios(session_id: str, expert_id: str, questions: list):
    """Saves the questions generated by the AI Journalist."""
    with get_connection() as conn:
        with conn.cursor() as cur:
            for q in questions:
                # Handle both string questions and dict questions
                q_text = q.get("question", str(q)) if isinstance(q, dict) else str(q)
                cur.execute("""
                    INSERT INTO scenarios (session_id, expert_id, question_text)
                    VALUES (%s, %s, %s)
                """, (session_id, expert_id, q_text))

def save_answers(session_id: str, expert_id: str, answers: list):
    """Saves the expert's manual answers."""
    with get_connection() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
            # Map answers back to scenarios by index (order they were inserted)
            cur.execute("SELECT id FROM scenarios WHERE session_id = %s ORDER BY created_at ASC", (session_id,))
            scenarios = cur.fetchall()
            for ans in answers:
                idx = ans.get("question_index", 0)
                if idx < len(scenarios):
                    scenario_id = scenarios[idx]["id"]
                    cur.execute("""
                        INSERT INTO expert_answers (scenario_id, expert_id, answer_text)
                        VALUES (%s, %s, %s)
                    """, (scenario_id, expert_id, ans.get("answer", "")))

def save_persona_manifest(session_id: str, expert_id: str, manifest: dict):
    """Saves the final compiled Persona Print."""
    with get_connection() as conn:
        with conn.cursor() as cur:
            comm_style = json.dumps(manifest.get("communication_style", {}))
            heuristics = json.dumps(manifest.get("heuristics", []))
            drop_zones = json.dumps(manifest.get("drop_zone_triggers", []))
            raw_manifest = json.dumps(manifest)
            cur.execute("""
                INSERT INTO persona_manifests (expert_id, session_id, communication_style, heuristics, drop_zone_triggers, raw_manifest_json)
                VALUES (%s, %s, %s, %s, %s, %s)
            """, (expert_id, session_id, comm_style, heuristics, drop_zones, raw_manifest))
