"""
skills/base/draft_skill.py

BaseSkill — Draft Text
SRP: One job — produce a text draft. No expert context. No persona.
"""

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..'))

from shared.interfaces.skill import BaseSkill, SkillParams, SkillResult


class DraftSkill(BaseSkill):
    """
    Raw capability: generate a structured text draft.
    Used as the base for most communication-type functional skills.

    Input params:
        template    : str   — What kind of draft? ("email", "report", "note")
        subject     : str   — Subject/title of the draft
        key_points  : list  — Bullet points to include
        recipient   : str   — Who is this addressed to?
        tone_hint   : str   — "formal", "empathetic", "brief" (overridden by persona in functional)
    """

    def get_skill_id(self) -> str:
        return "draft_text"

    def get_description(self) -> str:
        return "Generate a structured text draft (email, report, clinical note, etc.)"

    def execute(self, params: SkillParams) -> SkillResult:
        try:
            p = params.raw_params
            template = p.get("template", "email")
            subject = p.get("subject", "Follow-up")
            key_points = p.get("key_points", [])
            recipient = p.get("recipient", "Recipient")
            tone_hint = p.get("tone_hint", "professional")

            points_text = "\n".join(f"  - {pt}" for pt in key_points) if key_points else "  - (no specific points provided)"

            draft = (
                f"--- DRAFT {template.upper()} ---\n"
                f"To: {recipient}\n"
                f"Subject: {subject}\n"
                f"Tone: {tone_hint}\n\n"
                f"Key points to address:\n{points_text}\n\n"
                f"[Body to be generated by LLM with persona context injected]\n"
                f"--- END DRAFT ---"
            )

            return SkillResult(
                success=True,
                output=draft,
                skill_id=self.get_skill_id(),
                metadata={"template": template, "recipient": recipient},
            )

        except Exception as e:
            return SkillResult(
                success=False,
                output=None,
                skill_id=self.get_skill_id(),
                error_message=str(e),
            )
