-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- ─────────────────────────────────────────────────────────────────────────────
-- Table: experts
-- The actual human expert we are creating a persona for.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists experts (
    id          uuid primary key default uuid_generate_v4(),
    name        text not null,
    role        text not null,
    domain      text not null,
    created_at  timestamp with time zone default now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- Table: extraction_sessions
-- Tracks a specific interview session for an expert (LangGraph state).
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists extraction_sessions (
    id          uuid primary key default uuid_generate_v4(),
    expert_id   uuid references experts(id) on delete cascade,
    status      text default 'in_progress', -- 'in_progress', 'awaiting_answers', 'complete', 'failed'
    current_node text,
    error       text,
    langgraph_state jsonb default '{}'::jsonb,
    created_at  timestamp with time zone default now(),
    updated_at  timestamp with time zone default now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- Table: scenarios (The Questions)
-- The scenarios/questions generated by the AI Journalist for the expert.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists scenarios (
    id          uuid primary key default uuid_generate_v4(),
    session_id  uuid references extraction_sessions(id) on delete cascade,
    expert_id   uuid references experts(id) on delete cascade,
    question_text text not null,
    context     text,
    created_at  timestamp with time zone default now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- Table: expert_answers (The Answers)
-- The manual answers provided by the expert to the AI's scenarios.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists expert_answers (
    id          uuid primary key default uuid_generate_v4(),
    scenario_id uuid references scenarios(id) on delete cascade,
    expert_id   uuid references experts(id) on delete cascade,
    answer_text text not null,
    submitted_at timestamp with time zone default now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- Table: persona_manifests (The Final Persona Print)
-- The final compiled JSON persona created after the interview is complete.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists persona_manifests (
    id                   uuid primary key default uuid_generate_v4(),
    expert_id            uuid references experts(id) on delete cascade,
    session_id           uuid references extraction_sessions(id) on delete cascade,
    manifest_version     int default 1,
    communication_style  jsonb not null default '{}'::jsonb, 
    heuristics           jsonb not null default '[]'::jsonb, 
    drop_zone_triggers   jsonb not null default '[]'::jsonb, 
    confidence_threshold float default 0.70,
    shadow_approved      boolean default false,
    raw_manifest_json    jsonb not null default '{}'::jsonb, -- The full JSON print
    created_at           timestamp with time zone default now()
);
